# Example docker compose config.

version: "3.8"
services:
  shairport-sync:
    image: registry.nova.do/shairport-sync:dev
    network_mode: host
    restart: unless-stopped
    devices:
      - "/dev/snd"
    volumes:
      - ./volumes/shairport-sync/shairport-sync.conf:/etc/shairport-sync.conf