name: Classic on macOS with brew

on:
  push:
    branches: [ "development" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        brew update
        brew install automake
        brew install openssl
        brew install popt
        brew install libconfig
        brew install libao

    - name: Configure
      run: |
        export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
        export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
        export PATH="/usr/local/opt/openssl/bin:${PATH}"
        export PKG_CONFIG_PATH="/usr/local/opt/openssl@3/lib/pkgconfig"
        autoreconf -fi
        ./configure --with-os=darwin --with-ao --with-stdout --with-dns_sd --with-ssl=openssl
    
    - name: Make
      run: |
        make
