# Builds a docker image when a commit is made. Also pushes the build if the branch is 'master' or 'development'.

# Tag pattern
# 'master'      - rolling, rolling-classic
#Â 'development' - development, development-classic

name: Build and push docker (commit)

on:
  push:
    branches:
      - master
      - development

env:
  DOCKER_PLATFORMS: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
  NQPTP_BRANCH: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Set SHAIRPORT_SYNC_BRANCH env.
        run: echo "SHAIRPORT_SYNC_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Is branch "master"?
        if: ${{ env.SHAIRPORT_SYNC_BRANCH == 'master' }}
        run: |
          echo "IMAGE_TAG_BASE=rolling" >> $GITHUB_ENV

      - name: Is branch "development"?
        if: ${{ env.SHAIRPORT_SYNC_BRANCH == 'development' }}
        run: |
          echo "NQPTP_BRANCH=development" >> $GITHUB_ENV
          echo "IMAGE_TAG_BASE=development" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to Docker Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push (classic)
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          file: ./docker/classic/Dockerfile
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ env.IMAGE_TAG_BASE != '' }}
          tags: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG_BASE }}-classic
          build-args: |
            SHAIRPORT_SYNC_BRANCH=${{ env.SHAIRPORT_SYNC_BRANCH }}
 
      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          file: ./docker/Dockerfile
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: ${{ env.IMAGE_TAG_BASE != '' }}
          tags: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG_BASE }}
          build-args: |
            SHAIRPORT_SYNC_BRANCH=${{ env.SHAIRPORT_SYNC_BRANCH }}
            NQPTP_BRANCH=${{ env.NQPTP_BRANCH }}
